server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456

  data:
    redis:
      host: '127.0.0.1'
      port: 6379
      password: "123456"


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml